#pragma once

#include "frc/WPILib.h"
#include "Math.h"
using namespace frc;
class OI {
  private:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Joystick* xBoxControl;
    JoystickButton* ControlA;
    JoystickButton* ControlB;
    JoystickButton* Select;
    
    
    
  public:
    OI();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
    Joystick* getControlJoystick();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};